### ISSUE TITLE
Bad performance when using the Unity builder

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.Unity#1]
Running our performance test suite show bad performance both for receiving and sending.

With autofac:
```

---------------- Statistics ----------------
NumberOfMessages: 11199.0 (#)
Throughput: 3744.8 (msg/s)
Sending: 8999.2 (msg/s)
SendingInsideTX: 2050.2 (msg/s)

```

With unity:

```
---------------- Statistics ----------------
NumberOfMessages: 10007.0 (#)
Throughput: 163.5 (msg/s)
SendingInsideTX: 326.8 (msg/s)

```

**Comment by ramonsmits** [comment]
It seems that a customer is having Unity performance issues with v4.4.8 after updating from 4.4.3 and things that this is a regression.

**Comment by ramonsmits** [comment]
Release 4.4.8 is based on the code in the NServiceBus repo:
- https://github.com/Particular/NServiceBus/blob/4.4.8/src/ObjectBuilder.Unity/PropertyInjectionBuilderStrategy.cs#L43

This does not contain the fix present in this repository.

NServiceBus.Unity v5.0.0 is targeting Unity v3.0.0 and seem to contain the fix based on the tag commit history:

- https://github.com/Particular/NServiceBus.Unity/commits/5.0.0

**Comment by ramonsmits** [comment]
Closing this as issue #23 has been created to deal with this regression.
