### ISSUE TITLE
Incorrect release of versions 4.4.4 to 4.7.12

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Unity#23]
The latest release of NServiceBus.Unity for NServiceBus v4.x is NServiceBus.Unity version 4.4.3.1. All versions after this for NServiceBus v4.x has been accidentally been released due to the objectbuilders still being part of the Particular/NServiceBus v4 code base.

This causes an regression of issue #1

Connects to Particular/PlatformDevelopment#562

**Comment by mauroservienti** [comment]
@Particular/platform-dev-squad this is missing a proper task force, @ramonsmits please ping people to set up one.

**Comment by ramonsmits** [comment]
Build from Friday failed, test was hanging. Running AT's again.
