### ISSUE TITLE
Upgrade to v6 

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.Unity#24]
* [x] code changes, if any, required to upgrade to V6
* [x] tests
* [ ] release the Nuget package

Related to https://github.com/Particular/NServiceBus/issues/3076

**Comment by SimonCropp** [comment]
@malkinservicebus this is already done. we have a working sample. u can bump the nuget to the latest but it should be no code changes required

**Comment by mauroservienti** [comment]
@SimonCropp thanks, so the only thing that is missing is to publish a new nuget package, say v7.0.0 that targets NServiceBus V6, or can we relax the restrictions on the actual one?

**Comment by SimonCropp** [comment]
When we do a final of the core we will need to bump or the downstream nugets

**Comment by mauroservienti** [comment]
I'll this this open and update the description.

**Comment by johnsimons** [comment]
Should we close this and just have a single issue for what needs to be done as part of releasing everything ?

**Comment by mikeminutillo** [comment]
:+1:
