### ISSUE TITLE
Unity 5.3.2 is broken with NServiceBus.Unity 8.0.0

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Unity#63]
Source: https://eu1.salesforce.com/apex/Case?num=00033046

No further details yet. Maybe related to #58 as there Unity 5.3.1 resolved the broken behavior but likely 5.3.2 introduced a regression on their end.

I do not see any related issues here: https://github.com/unitycontainer/unity/issues and their 5.3.1 release tag seems missing https://github.com/unitycontainer/unity/tags

**Comment by ramonsmits** [comment]
Also created https://github.com/unitycontainer/unity/issues/168

**Comment by ramonsmits** [comment]
Commented https://github.com/unitycontainer/unity/issues/168#issuecomment-352720426

**Comment by WilliamBZA** [comment]
8.1 will be released to work with 5.5.0 of unity and higher.

**Comment by WilliamBZA** [comment]
8.1 has been released.
