### ISSUE TITLE
Exception during UseContainer<UnityBuilder> on endpointconfiguration-instance

### ISSUE THREAD

**Issue by haraldv** [Particular/NServiceBus.Unity#70]
NServiceBus 6.3.4
NServiceBus.Unity 8.1.0
UnityContainer 5.7.3

When registering the container for nservicebus I get an exception.

Code:
UnityContainer container = new UnityContainer();
            endpointConfiguration.UseContainer<UnityBuilder>(
                customizations =>
                {
                    customizations.UseExistingContainer(container);
                });

Exception:
Method not found: 'Unity.Strategy.IStagedStrategyChain`2<Unity.Builder.Strategy.IBuilderStrategy,Unity.Builder.UnityBuildStage> Unity.Extension.ExtensionContext.get_Strategies()'.

Possibly related to a breaking change on unity?
https://github.com/unitycontainer/abstractions/releases/tag/2.4.0.150
Unity has retired an interface and instead offered the code as extension methods. This required recompile of dependent code.

**Comment by WilliamBZA** [comment]
😞 It seems the Unity guys are determined to ignore Semver. They've done this already in version 5 before. https://github.com/Particular/NServiceBus.Unity/issues/63

**Comment by WilliamBZA** [comment]
I'll start working on a new release

**Comment by andreasohlund** [comment]
Raised a PR https://github.com/Particular/NServiceBus.Unity/pull/71

**Comment by WilliamBZA** [comment]
I've submitted a bug at Unity. It appears there is a breaking change in how strategies are executed and the order of registrations.

https://github.com/unitycontainer/unity/issues/214
