### ISSUE TITLE
UnityObjectBuilder does not remove itself correctly from existing containers on dispose

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/NServiceBus.Unity#73]
Original bug found [here](https://discuss.particular.net/t/using-existing-unitycontainer-and-getting-object-disposed-error-for-unityobjectbuilder)

When the `UnityObjectBuilder` is created, it injects 2 Container Extensions into the container that is provided to it. If an existing container is used, that means the extensions could have a longer life than the instance of `UnityObjectBuilder`. [One of these extensions](https://github.com/Particular/NServiceBus.Unity/blob/develop/src/NServiceBus.Unity/PropertyInjectionContainerExtension.cs#L12) has a dependency on the instance of `UnityObjectBuilder` itself.

This causes problems when the `UnityObjectBuilder` is disposed, but the container is still used elsewhere. In this scenario, the extension is still active, but when it tries to execute it uses a reference to the disposed `UnityObjectBuilder` resulting in an `ObjectDisposedException` being thrown.

**Comment by WilliamBZA** [comment]
Release made for 6.2.2.

**Comment by boblangley** [comment]
NServiceBus.Unity 7.0.1 and 8.1.1 with these changes has been released.
